services:

  pg:
    image: postgres
    environment:
      POSTGRES_DB: agb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    ports:
      - "8080:8080"

  #  pgadmin:
  #    image: dpage/pgadmin4
  #    environment:
  #      PGADMIN_DEFAULT_EMAIL: admin@admin.org
  #      PGADMIN_DEFAULT_PASSWORD: admin
  #      PGADMIN_CONFIG_SERVER_MODE: 'False'
  #    ports:
  #      - "5050:80"

  app:
    build: agb-application/
    command: python3 main.py
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped