services:

  postgres:
    container_name: postgres
    restart: always
    networks:
      - db-network
    image: postgres:17
    environment:
      POSTGRES_DB: agb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_HOST_AUTH_METHOD: scram-sha-256
      PGDATA: /var/lib/postgresql/data/pgdata/
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d agb -U user" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./pg-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    command: postgres -c shared_buffers=128MB -c max_connections=100

  #  adminer:
  #    image: adminer
  #    ports:
  #      - "8080:8080"

  #  pgadmin:
  #    image: dpage/pgadmin4
  #    environment:
  #      PGADMIN_DEFAULT_EMAIL: admin@admin.org
  #      PGADMIN_DEFAULT_PASSWORD: admin
  #      PGADMIN_CONFIG_SERVER_MODE: 'False'
  #    ports:
  #      - "5050:80"

  app:
    container_name: app
    networks:
      - db-network
    build: agb-application/
    command: "python3 main.py || alembic upgrade head"
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "80:80"
      - "443:443"
    restart: always
    environment:
      - DATABASE_URL=postgresql+asyncpg://user:password@postgres:5432/agb

networks:
  db-network:
    driver: bridge

volumes:
  postgres-data: