services:

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: agb
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d agb -U user" ]
      interval: 5s
      timeout: 5s
      retries: 5





  #  adminer:
  #    image: adminer
  #    ports:
  #      - "8080:8080"

  #  pgadmin:
  #    image: dpage/pgadmin4
  #    environment:
  #      PGADMIN_DEFAULT_EMAIL: admin@admin.org
  #      PGADMIN_DEFAULT_PASSWORD: admin
  #      PGADMIN_CONFIG_SERVER_MODE: 'False'
  #    ports:
  #      - "5050:80"

  app:
    build: agb-application/
    command: "python3 main.py && alembic upgrade head"
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    environment:
      DATABASE_URL: postgresql+asyncpg://user:password@postgres:5432/agb

