"""Adding age field to user model

Revision ID: cab35eff2b51
Revises: 64b08b2d80f2
Create Date: 2025-02-10 10:08:18.554870

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "cab35eff2b51"
down_revision: Union[str, None] = "64b08b2d80f2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("age", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "age")
    # ### end Alembic commands ###
