"""Adding FIO and image fields to user model

Revision ID: 64b08b2d80f2
Revises: d0c0a7d63551
Create Date: 2025-02-10 09:52:47.819996

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "64b08b2d80f2"
down_revision: Union[str, None] = "d0c0a7d63551"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("name", sa.String(length=50), nullable=True)
    )
    op.add_column(
        "users", sa.Column("surname", sa.String(length=50), nullable=True)
    )
    op.add_column(
        "users", sa.Column("patronymic", sa.String(length=50), nullable=True)
    )
    op.add_column(
        "users", sa.Column("image", sa.String(length=255), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "image")
    op.drop_column("users", "patronymic")
    op.drop_column("users", "surname")
    op.drop_column("users", "name")
    # ### end Alembic commands ###
