"""create users states

Revision ID: 8d849da98254
Revises: 449147e9acf4
Create Date: 2025-01-23 15:59:26.927276

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8d849da98254"
down_revision: Union[str, None] = "449147e9acf4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("role", sa.String(length=50), nullable=False)
    )
    op.add_column("users", sa.Column("is_active", sa.Boolean(), nullable=True))
    op.add_column(
        "users", sa.Column("super_user", sa.Boolean(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "super_user")
    op.drop_column("users", "is_active")
    op.drop_column("users", "role")
    # ### end Alembic commands ###
